// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvl1ycaA9ZFb2qV2XPXby302F5N-0MDw0',
    appId: '1:933572055793:web:3da67315d05545e3d58f50',
    messagingSenderId: '933572055793',
    projectId: 'chat-revamp-2bfbb',
    authDomain: 'chat-revamp-2bfbb.firebaseapp.com',
    storageBucket: 'chat-revamp-2bfbb.appspot.com',
    measurementId: 'G-TLL67RJZKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBDiuYFrCnhuQrlOs32qoTYvfHkkuX-k0',
    appId: '1:933572055793:android:edee5cb3d564b39bd58f50',
    messagingSenderId: '933572055793',
    projectId: 'chat-revamp-2bfbb',
    storageBucket: 'chat-revamp-2bfbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5nbNykEYdI_Q_oQ2glRZNWMODtiysGaY',
    appId: '1:933572055793:ios:78cc8a3b1fa182cfd58f50',
    messagingSenderId: '933572055793',
    projectId: 'chat-revamp-2bfbb',
    storageBucket: 'chat-revamp-2bfbb.appspot.com',
    iosBundleId: 'com.example.chatRevamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5nbNykEYdI_Q_oQ2glRZNWMODtiysGaY',
    appId: '1:933572055793:ios:55894bd6580f1bded58f50',
    messagingSenderId: '933572055793',
    projectId: 'chat-revamp-2bfbb',
    storageBucket: 'chat-revamp-2bfbb.appspot.com',
    iosBundleId: 'com.example.chatRevamp.RunnerTests',
  );
}
